# Generated by Django 6.0 on 2026-01-18 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Time')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('operating_system', models.CharField(blank=True, default='', max_length=100, verbose_name='Operating System')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='Browser')),
                ('browser_version', models.CharField(blank=True, default='', max_length=50, verbose_name='Browser Version')),
                ('device', models.CharField(blank=True, default='', max_length=100, verbose_name='Device')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User Agent String')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Login Log',
                'verbose_name_plural': 'Login Logs',
                'ordering': ['-login_time'],
            },
        ),
    ]
