# Generated by Django 6.0 on 2026-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name (e.g. Meta Pixel)', max_length=100)),
                ('script_id', models.SlugField(help_text='Unique ID for the script tag (e.g. meta-pixel). Used as the script element id.', max_length=100, unique=True)),
                ('provider', models.CharField(blank=True, help_text='Provider name (e.g. facebook, google) for reference.', max_length=50)),
                ('script_content', models.TextField(help_text='JavaScript code to run inside a script tag. Do not include <script> tags.')),
                ('noscript_content', models.TextField(blank=True, help_text='Optional HTML for <noscript> fallback (e.g. tracking pixel img).')),
                ('placement', models.CharField(choices=[('head', 'Head'), ('body', 'Body')], default='body', help_text='Where to inject the script in the page.', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order when multiple tracking codes are present (lower first).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tracking code',
                'verbose_name_plural': 'Tracking codes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
