# Generated by Django 6.0 on 2026-02-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_simplify_tracking_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingcode',
            name='script_content',
            field=models.TextField(blank=True, help_text='Paste the full pixel code (e.g. Meta Pixel: comments, <script> and <noscript>). Rendered on the frontend as-is.'),
        ),
    ]
