# Generated by Django 6.0 on 2026-02-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_trackingcode_script_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingcode',
            name='script_content',
        ),
        migrations.AddField(
            model_name='trackingcode',
            name='pixel_id',
            field=models.CharField(blank=True, help_text='Meta (Facebook) Pixel ID (e.g. 1234567890123456).', max_length=50),
        ),
    ]
