# Generated by Django 6.0 on 2025-12-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(blank=True, help_text='Product size selected by customer', max_length=50),
        ),
    ]
