# Generated by Django 6.0 on 2025-12-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_zip',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
