# Generated by Django 6.0 on 2025-12-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_shipping_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='steadfast_consignment_id',
            field=models.IntegerField(blank=True, help_text='Steadfast consignment ID', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_status',
            field=models.CharField(blank=True, help_text='Current Steadfast delivery status', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='steadfast_tracking_code',
            field=models.CharField(blank=True, help_text='Steadfast tracking code', max_length=50),
        ),
    ]
