# Generated by Django 6.0 on 2026-01-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.URLField(blank=True, help_text='Product image URL at time of order', max_length=500),
        ),
    ]
