# Generated by Django 6.0 on 2026-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.CharField(blank=True, help_text='Product color selected by customer', max_length=100),
        ),
    ]
