# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_size',
            field=models.CharField(
                blank=True,
                help_text='Product size display string (e.g. "Shirt Size: M, Pants Size: 30")',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_sizes',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Selected sizes by label, e.g. {"Shirt Size": "M", "Pants Size": "30"}',
            ),
        ),
    ]
