# Generated by Django 6.0 on 2025-12-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_migrate_price_to_regular_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('womens', 'Womens'), ('combo', 'Combo')], default='men', help_text='Product category', max_length=10),
        ),
    ]
