# Generated by Django 6.0 on 2026-01-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('womens', 'Womens'), ('combo', 'Combo'), ('shirt-combo', 'Shirt Combo'), ('panjabi-combo', 'Panjabi Combo'), ('shirts', 'Shirts'), ('panjabi', 'Panjabi')], default='men', help_text='Product category', max_length=20),
        ),
    ]
