# Generated by Django 6.0 on 2026-02-03 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productcolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Hero banner image displayed on the homepage', upload_to='hero/')),
                ('title', models.CharField(blank=True, help_text='Optional headline text overlay on the hero', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtext overlay on the hero', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Only the active hero image is shown on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Image',
                'verbose_name_plural': 'Hero Images',
                'ordering': ['-created_at'],
            },
        ),
    ]
