# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size_options',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='List of size dimensions, e.g. [{"label": "Shirt Size", "options": ["S", "M", "L"]}]. Empty uses default "Size: One Size".',
            ),
        ),
    ]
